### ISSUE TITLE
[Security] Secure video storage

### ISSUE THREAD

**Issue by GwynbleiddRU** [TE-Flutter/tunelike-app-sq#12]
_I always used other services to keep my videos and just used a link for them_ (if smb is interested i came up with using discord, - just send a file to your alt in chat and it will be available from there for a year).

Now we need your advice on how to store them independently from other services (the possible solution is just  to keep filed on the server side but in case.. Maybe there is another way)

**Comment by aabounegm** [comment]
Firebase Storage
